export default function TermsSettingsPage() {
  return (
    <div className="space-y-6">
      <div>
        <h3 className="text-lg font-medium">Terms & Conditions</h3>
        <p className="text-sm text-muted-foreground">
          Please read our terms and conditions carefully.
        </p>
      </div>
      <div className="text-sm text-foreground space-y-4">
        <h4 className="font-semibold">1. Acceptance of Terms</h4>
        <p>By accessing and using BreatheEasy, you accept and agree to be bound by the terms and provision of this agreement. The data provided is for informational purposes only and should not be used for medical emergencies.</p>
        
        <h4 className="font-semibold">2. Disclaimer of Warranty</h4>
        <p>The AQI data, forecasts, and health advice are generated by AI models and may contain inaccuracies. We do not guarantee the accuracy or reliability of the information provided.</p>
        
        <h4 className="font-semibold">3. Limitation of Liability</h4>
        <p>BreatheEasy and its creators will not be liable for any direct, indirect, incidental, special or consequential damages resulting from the use or inability to use the service.</p>
      </div>
    </div>
  );
}
