import {
  Accordion,
  AccordionContent,
  AccordionItem,
  AccordionTrigger,
} from "@/components/ui/accordion";

export default function FaqSettingsPage() {
  return (
    <div className="space-y-6">
      <div>
        <h3 className="text-lg font-medium">Frequently Asked Questions</h3>
        <p className="text-sm text-muted-foreground">
          Find answers to common questions about BreatheEasy.
        </p>
      </div>
      <Accordion type="single" collapsible className="w-full">
        <AccordionItem value="item-1">
          <AccordionTrigger>What is AQI?</AccordionTrigger>
          <AccordionContent>
            The Air Quality Index (AQI) is a scale used to report the quality of the air. It measures how clean or polluted the air is, and what associated health effects might be a concern for you.
          </AccordionContent>
        </AccordionItem>
        <AccordionItem value="item-2">
          <AccordionTrigger>How accurate are the predictions?</AccordionTrigger>
          <AccordionContent>
            Our predictions are generated by AI models based on historical and regional data patterns. While they provide a good estimate, they are for informational purposes only and may differ from actual conditions.
          </AccordionContent>
        </AccordionItem>
        <AccordionItem value="item-3">
          <AccordionTrigger>Can I use this app for medical advice?</AccordionTrigger>
          <AccordionContent>
            No. The health advice provided is AI-generated and should not be considered a substitute for professional medical advice, diagnosis, or treatment. Always seek the advice of your physician or other qualified health provider with any questions you may have regarding a medical condition.
          </AccordionContent>
        </AccordionItem>
      </Accordion>
    </div>
  );
}
